### ISSUE TITLE
picture problem

### ISSUE THREAD

**Issue by zhuangjianbin** [ZeKarlish/boustrophedon_cellular_decomposition#1]
May I ask if this image is a vector?

**Comment by Karlish-git** [comment]
The input image should be a .png file. I'd suggest looking at original repo that I cloned from:  [samialperen/boustrophedon_cellular_decomposition](https://github.com/samialperen/boustrophedon_cellular_decomposition)

The code I have in this repo may not work as I ended up rewriting big parts, but don't recal if I ever pushed completed code to GitHub
